package com.ray.service.impl;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.ray.constant.AdminPermissions;import com.ray.dto.CommissionRuleUpdateDTO;import com.ray.entity.*;import com.ray.exception.BusinessException;import com.ray.mapper.*;import com.ray.result.PageResult;import com.ray.service.*;import com.ray.utils.converter.IdUtils;import com.ray.utils.generator.RedisIdWorker;import com.ray.vo.*;import java.time.LocalDateTime;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class FinanceServiceImpl implements FinanceService {private final CommissionRuleMapper ruleMapper;private final FundLedgerEntryMapper ledgerMapper;private final AdminAuthService admin;private final MerchantAuthService merchant;private final RedisIdWorker ids;public FinanceServiceImpl(CommissionRuleMapper ruleMapper,FundLedgerEntryMapper ledgerMapper,AdminAuthService admin,MerchantAuthService merchant,RedisIdWorker ids){this.ruleMapper=ruleMapper;this.ledgerMapper=ledgerMapper;this.admin=admin;this.merchant=merchant;this.ids=ids;}
 @Override public CommissionRuleVO rule(String shopId){admin.requirePermission(AdminPermissions.COMMISSION_MANAGE);Long sid=shopId==null?null:IdUtils.parse(shopId,"shopId");CommissionRule r=ruleMapper.selectOne(new QueryWrapper<CommissionRule>().eq(sid!=null,"shop_id",sid).orderByDesc("effective_from").last("LIMIT 1"));return r==null?new CommissionRuleVO(null,shopId,500,LocalDateTime.now(),null,0):toRule(r);}
 @Override @Transactional public CommissionRuleVO update(String shopId,CommissionRuleUpdateDTO req,String key){admin.requirePermission(AdminPermissions.COMMISSION_MANAGE);Long sid=shopId==null?null:IdUtils.parse(shopId,"shopId");CommissionRule r=new CommissionRule().setId(ids.nextId("commission-rule")).setShopId(sid).setRateBps(req.rateBps()).setEffectiveFrom(LocalDateTime.now()).setVersion(req.version()+1);ruleMapper.insert(r);return toRule(r);}
 @Override public PageResult<FundLedgerEntryVO> ledger(int page,int size){admin.requirePermission(AdminPermissions.COMMISSION_MANAGE);Page<FundLedgerEntry> p=ledgerMapper.selectPage(new Page<>(page,size),new QueryWrapper<FundLedgerEntry>().orderByDesc("occurred_time","id"));return new PageResult<>(p.getRecords().stream().map(this::toLedger).toList(),page,size,p.getTotal());}
 @Override public MerchantFinanceSummaryVO merchantSummary(){MerchantAccount a=merchant.requireCurrentAccount();if(a.getShopId()==null)throw BusinessException.forbidden("MERCHANT_ACTIVATION_REQUIRED","商户账号尚未激活");var list=ledgerMapper.selectList(new QueryWrapper<FundLedgerEntry>().eq("shop_id",a.getShopId()));long frozen=0,recognized=0,commission=0;for(var e:list){if("PAYMENT_FROZEN".equals(e.getEntryType()))frozen+=e.getAmount();if("REDEMPTION_RECOGNIZED".equals(e.getEntryType()))recognized+=e.getAmount();if("COMMISSION_RECOGNIZED".equals(e.getEntryType()))commission+=e.getAmount();}return new MerchantFinanceSummaryVO(frozen,recognized,commission,recognized-commission);}
 @Override public void append(FundLedgerEntryVO e){FundLedgerEntry x=new FundLedgerEntry().setId(ids.nextId("ledger-entry")).setShopId(e.shopId()==null?null:Long.valueOf(e.shopId())).setOrderId(e.orderId()==null?null:Long.valueOf(e.orderId())).setVoucherId(e.voucherId()==null?null:Long.valueOf(e.voucherId())).setBusinessEventId(e.businessEventId()).setEntryType(e.entryType()).setAccountSide(e.accountSide()).setAmount(e.amount()).setCommissionRateBps(e.commissionRateBps()).setOccurredTime(e.occurredTime()==null?LocalDateTime.now():e.occurredTime());try{ledgerMapper.insert(x);}catch(DuplicateKeyException ignored){}}
 private CommissionRuleVO toRule(CommissionRule r){return new CommissionRuleVO(IdUtils.format(r.getId()),r.getShopId()==null?null:IdUtils.format(r.getShopId()),r.getRateBps(),r.getEffectiveFrom(),r.getEffectiveTo(),r.getVersion());}private FundLedgerEntryVO toLedger(FundLedgerEntry e){return new FundLedgerEntryVO(IdUtils.format(e.getId()),IdUtils.format(e.getShopId()),IdUtils.format(e.getOrderId()),IdUtils.format(e.getVoucherId()),e.getBusinessEventId(),e.getEntryType(),e.getAccountSide(),e.getAmount(),e.getCommissionRateBps(),e.getOccurredTime());}}
