package com.ray.service.impl;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.ray.constant.AdminPermissions;import com.ray.entity.*;import com.ray.exception.BusinessException;import com.ray.mapper.*;import com.ray.realtime.RealtimeEventPublisher;import com.ray.result.PageResult;import com.ray.service.*;import com.ray.utils.converter.IdUtils;import com.ray.utils.generator.RedisIdWorker;import com.ray.vo.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.time.*;import java.util.*;import java.util.stream.Collectors;import java.util.zip.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class SettlementServiceImpl implements SettlementService {private final SettlementBatchMapper batchMapper;private final SettlementItemMapper itemMapper;private final FundLedgerEntryMapper ledgerMapper;private final AdminAuthService admin;private final MerchantAuthService merchant;private final RedisIdWorker ids;private RealtimeEventPublisher realtimeEvents;public SettlementServiceImpl(SettlementBatchMapper batchMapper,SettlementItemMapper itemMapper,FundLedgerEntryMapper ledgerMapper,AdminAuthService admin,MerchantAuthService merchant,RedisIdWorker ids){this.batchMapper=batchMapper;this.itemMapper=itemMapper;this.ledgerMapper=ledgerMapper;this.admin=admin;this.merchant=merchant;this.ids=ids;}@Autowired(required=false) void setRealtimeEvents(RealtimeEventPublisher realtimeEvents){this.realtimeEvents=realtimeEvents;}
 @Override public PageResult<SettlementBatchVO> list(int page,int size,boolean isAdmin){Long shop=null;if(isAdmin)admin.requirePermission(AdminPermissions.SETTLEMENT_MANAGE);else{var a=merchant.requireCurrentAccount();shop=a.getShopId();if(shop==null)throw BusinessException.forbidden("MERCHANT_ACTIVATION_REQUIRED","商户账号尚未激活");}QueryWrapper<SettlementBatch> q=new QueryWrapper<>();if(shop!=null)q.eq("shop_id",shop);Page<SettlementBatch> p=batchMapper.selectPage(new Page<>(page,size),q.orderByDesc("settlement_date","id"));return new PageResult<>(p.getRecords().stream().map(this::toVO).toList(),page,size,p.getTotal());}
 @Override public SettlementBatchVO get(Long id,boolean isAdmin){SettlementBatch b=batchMapper.selectById(id);if(b==null)throw BusinessException.notFound("SETTLEMENT_NOT_FOUND","结算批次不存在");if(isAdmin)admin.requirePermission(AdminPermissions.SETTLEMENT_MANAGE);else{var a=merchant.requireCurrentAccount();if(!Objects.equals(a.getShopId(),b.getShopId()))throw BusinessException.notFound("SETTLEMENT_NOT_FOUND","结算批次不存在");}return toVO(b);}
 @Override @Transactional public SettlementBatchVO retry(Long id,String key){admin.requirePermission(AdminPermissions.SETTLEMENT_MANAGE);SettlementBatch b=batchMapper.selectById(id);if(b==null)throw BusinessException.notFound("SETTLEMENT_NOT_FOUND","结算批次不存在");if("SUCCEEDED".equals(b.getStatus()))throw BusinessException.conflict("SETTLEMENT_ALREADY_SUCCEEDED","结算已完成");b.setStatus("SUCCEEDED").setFailureReason(null).setProcessedTime(LocalDateTime.now());batchMapper.updateById(b);if(realtimeEvents!=null)realtimeEvents.publish("SETTLEMENT_UPDATED",id.toString(),b.getShopId());return toVO(b);}
 @Override @Transactional public void generateForDate(LocalDate settlementDate){
  if(settlementDate==null)throw BusinessException.badRequest("SETTLEMENT_DATE_REQUIRED","结算日期不能为空");
  LocalDate ledgerDate=settlementDate.minusDays(1); LocalDateTime from=ledgerDate.atStartOfDay(); LocalDateTime to=settlementDate.atStartOfDay();
  List<FundLedgerEntry> entries=ledgerMapper.selectList(new QueryWrapper<FundLedgerEntry>().ge("occurred_time",from).lt("occurred_time",to).isNotNull("shop_id")
    .in("entry_type","REDEMPTION_RECOGNIZED","SERVICE_FEE_RECOGNIZED","COMMISSION_RECOGNIZED",
      "REDEMPTION_REVERSED","SERVICE_FEE_REVERSED","COMMISSION_REVERSED",
      "REFUND_REVENUE_REVERSED","SERVICE_FEE_REFUNDED","SETTLEMENT_ADJUSTMENT")
    .orderByAsc("shop_id","occurred_time","id"));
  Map<Long,List<FundLedgerEntry>> byShop=entries.stream().collect(Collectors.groupingBy(FundLedgerEntry::getShopId,LinkedHashMap::new,Collectors.toList()));
  byShop.forEach((shopId,shopEntries)->{
   if(batchMapper.findByShopDate(shopId,settlementDate)!=null)return;
   SettlementBatch batch=new SettlementBatch().setId(ids.nextId("settlement-batch")).setShopId(shopId).setSettlementDate(settlementDate)
     .setStatus("SUCCEEDED").setTotalAmount(shopEntries.stream().mapToLong(this::settlementAmount).sum()).setVersion(0).setProcessedTime(LocalDateTime.now());
   batchMapper.insert(batch);
   for(FundLedgerEntry entry:shopEntries){
    itemMapper.insert(new SettlementItem().setId(ids.nextId("settlement-item")).setBatchId(batch.getId()).setLedgerEntryId(entry.getId()).setAmount(settlementAmount(entry)));
   }
   if(realtimeEvents!=null)realtimeEvents.publish("SETTLEMENT_UPDATED",batch.getId().toString(),shopId);
  });
 }
 private long settlementAmount(FundLedgerEntry entry){
  long amount=entry.getAmount()==null?0:entry.getAmount();
  if("SERVICE_FEE_RECOGNIZED".equals(entry.getEntryType())||"COMMISSION_RECOGNIZED".equals(entry.getEntryType())) return -Math.abs(amount);
  if("SERVICE_FEE_REVERSED".equals(entry.getEntryType())||"COMMISSION_REVERSED".equals(entry.getEntryType())
    ||"SERVICE_FEE_REFUNDED".equals(entry.getEntryType())) return Math.abs(amount);
  return amount>0&&"DEBIT".equals(entry.getAccountSide())?-amount:amount;
 }
 @Override public byte[] export(String resource,boolean isAdmin){if(isAdmin)admin.requirePermission(AdminPermissions.SETTLEMENT_MANAGE);else merchant.requireCurrentAccount();List<String[]> rows=new ArrayList<>();rows.add(new String[]{"ID","门店ID","金额(分)","状态","时间"});if("ledger".equals(resource)){for(FundLedgerEntry e:ledgerMapper.selectList(new QueryWrapper<FundLedgerEntry>().orderByDesc("occurred_time").last("LIMIT 10000")))rows.add(new String[]{IdUtils.format(e.getId()),IdUtils.format(e.getShopId()),String.valueOf(e.getAmount()),e.getEntryType(),String.valueOf(e.getOccurredTime())});}else{for(SettlementBatch b:batchMapper.selectList(new QueryWrapper<SettlementBatch>().orderByDesc("settlement_date").last("LIMIT 10000")))rows.add(new String[]{IdUtils.format(b.getId()),IdUtils.format(b.getShopId()),String.valueOf(b.getTotalAmount()),b.getStatus(),String.valueOf(b.getSettlementDate())});}return xlsx(rows);}
 private SettlementBatchVO toVO(SettlementBatch b){return new SettlementBatchVO(IdUtils.format(b.getId()),IdUtils.format(b.getShopId()),b.getSettlementDate(),b.getStatus(),b.getTotalAmount(),b.getFailureReason(),b.getProcessedTime());}
 private byte[] xlsx(List<String[]> rows){try{ByteArrayOutputStream out=new ByteArrayOutputStream();try(ZipOutputStream zip=new ZipOutputStream(out)){put(zip,"[Content_Types].xml","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/></Types>");put(zip,"_rels/.rels","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");put(zip,"xl/workbook.xml","<?xml version=\"1.0\" encoding=\"UTF-8\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Roamly\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>");put(zip,"xl/_rels/workbook.xml.rels","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/></Relationships>");StringBuilder sheet=new StringBuilder("<?xml version=\"1.0\" encoding=\"UTF-8\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetData>");int row=1;for(String[] values:rows){sheet.append("<row r=\"").append(row++).append("\">");for(int i=0;i<values.length;i++){String value=values[i]==null?"":values[i].replace("&","&amp;").replace("<","&lt;").replace(">","&gt;");if(value.startsWith("=")||value.startsWith("+")||value.startsWith("-")||value.startsWith("@"))value="'"+value;sheet.append("<c r=\"").append((char)('A'+i)).append(row-1).append("\" t=\"inlineStr\"><is><t>").append(value).append("</t></is></c>");}sheet.append("</row>");}sheet.append("</sheetData></worksheet>");put(zip,"xl/worksheets/sheet1.xml",sheet.toString());}return out.toByteArray();}catch(IOException e){throw new BusinessException(500,"EXPORT_FAILED","导出文件生成失败",e);}}
 private void put(ZipOutputStream z,String n,String s)throws IOException{z.putNextEntry(new ZipEntry(n));z.write(s.getBytes(StandardCharsets.UTF_8));z.closeEntry();}
}
