package com.ray.service.impl;
import cn.hutool.crypto.digest.DigestUtil;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.ray.constant.AdminPermissions;
import com.ray.dto.*;
import com.ray.entity.*;
import com.ray.enums.*;
import com.ray.exception.BusinessException;
import com.ray.mapper.*;
import com.ray.result.PageResult;
import com.ray.service.*;
import com.ray.utils.converter.IdUtils;
import com.ray.utils.generator.RedisIdWorker;
import com.ray.vo.*;
import java.time.*;
import java.util.UUID;
import java.util.concurrent.TimeUnit;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
@Service
public class VoucherRedemptionServiceImpl implements VoucherRedemptionService {
 private static final String PREVIEW="roamly:redemption:preview:";
 private final UserVoucherMapper voucherMapper; private final VoucherRedemptionMapper redemptionMapper; private final VoucherProductMapper productMapper; private final MerchantAuthService merchantAuth; private final AdminAuthService adminAuth; private final StringRedisTemplate redis; private final RedisIdWorker idWorker; private final MerchantAuditService audit;
 public VoucherRedemptionServiceImpl(UserVoucherMapper voucherMapper,VoucherRedemptionMapper redemptionMapper,VoucherProductMapper productMapper,MerchantAuthService merchantAuth,AdminAuthService adminAuth,StringRedisTemplate redis,RedisIdWorker idWorker,MerchantAuditService audit){this.voucherMapper=voucherMapper;this.redemptionMapper=redemptionMapper;this.productMapper=productMapper;this.merchantAuth=merchantAuth;this.adminAuth=adminAuth;this.redis=redis;this.idWorker=idWorker;this.audit=audit;}
 private MerchantAccount operator(){MerchantAccount a=merchantAuth.requireCurrentAccount();if(!MerchantAccountStatus.ACTIVE.name().equals(a.getStatus())||a.getShopId()==null)throw BusinessException.forbidden("MERCHANT_ACTIVATION_REQUIRED","商户账号尚未激活");return a;}
 @Override public VoucherRedemptionPreviewVO preview(VoucherRedemptionPreviewRequest req){MerchantAccount a=operator();UserVoucher v=voucherMapper.findByCodeHmac(DigestUtil.sha256Hex(req.code()));validateVoucher(a,v);VoucherProduct p=productMapper.selectById(v.getProductId());long consumption=req.consumptionAmount()==null?0:req.consumptionAmount();long discount=calculateDiscount(p,consumption);String token=UUID.randomUUID().toString().replace("-","");redis.opsForValue().set(PREVIEW+token,v.getId()+"|"+a.getShopId()+"|"+a.getId()+"|"+consumption+"|"+discount,5,TimeUnit.MINUTES);return new VoucherRedemptionPreviewVO(token,IdUtils.format(v.getId()),v.getVoucherCodeLast4(),p==null?null:p.getTitle(),remaining(v),consumption,discount,LocalDateTime.now().plusMinutes(5));}
 @Override @Transactional public VoucherRedemptionVO confirm(VoucherRedemptionConfirmRequest req,String key){MerchantAccount a=operator();VoucherRedemption old=redemptionMapper.selectOne(new QueryWrapper<VoucherRedemption>().eq("shop_id",a.getShopId()).eq("idempotency_key",key));if(old!=null)return toVO(old);String value=redis.opsForValue().getAndDelete(PREVIEW+req.previewToken());if(value==null)throw BusinessException.conflict("REDEMPTION_PREVIEW_EXPIRED","核销预览已过期");String[] parts=value.split("\\|");Long voucherId=Long.valueOf(parts[0]);if(!a.getShopId().equals(Long.valueOf(parts[1]))||!a.getId().equals(Long.valueOf(parts[2])))throw BusinessException.forbidden("REDEMPTION_PREVIEW_FORBIDDEN","核销预览不属于当前账号");UserVoucher v=voucherMapper.selectById(voucherId);validateVoucher(a,v);int before=remaining(v);int after=before-1;int changed=voucherMapper.update(null,new UpdateWrapper<UserVoucher>().eq("id",voucherId).eq("remaining_use_count",before).in("status",UserVoucherStatus.UNUSED.name(),UserVoucherStatus.PARTIALLY_USED.name()).set("remaining_use_count",after).set("status",after==0?UserVoucherStatus.USED.name():UserVoucherStatus.PARTIALLY_USED.name()).set(after==0,"use_time",LocalDateTime.now()));if(changed!=1)throw BusinessException.conflict("VOUCHER_ALREADY_REDEEMED","券状态已变化");VoucherRedemption r=new VoucherRedemption().setId(idWorker.nextId("voucher-redemption")).setVoucherId(voucherId).setShopId(a.getShopId()).setMerchantAccountId(a.getId()).setUseCount(1).setConsumptionAmount(Long.valueOf(parts[3])).setDiscountAmount(Long.valueOf(parts[4])).setStatus("SUCCEEDED").setIdempotencyKey(key).setRedeemedTime(LocalDateTime.now());redemptionMapper.insert(r);audit.record(a.getId(),"VOUCHER_REDEEMED","USER_VOUCHER",voucherId.toString(),"SUCCEEDED",null);return toVO(r);}
 @Override @Transactional public VoucherRedemptionVO reverse(Long id,VoucherRedemptionReversalRequest req,String key){MerchantAccount a=operator();if(MerchantRole.VERIFIER.name().equals(a.getRole()))throw BusinessException.forbidden("REDEMPTION_REVERSAL_FORBIDDEN","核销员无权撤销");VoucherRedemption r=redemptionMapper.selectById(id);if(r==null||!a.getShopId().equals(r.getShopId()))throw BusinessException.notFound("REDEMPTION_NOT_FOUND","核销记录不存在");if(!"SUCCEEDED".equals(r.getStatus()))return toVO(r);UserVoucher v=voucherMapper.selectById(r.getVoucherId());int restored=Math.min(v.getTotalUseCount()==null?1:v.getTotalUseCount(),remaining(v)+1);voucherMapper.update(null,new UpdateWrapper<UserVoucher>().eq("id",v.getId()).set("remaining_use_count",restored).set("status",restored==(v.getTotalUseCount()==null?1:v.getTotalUseCount())?UserVoucherStatus.UNUSED.name():UserVoucherStatus.PARTIALLY_USED.name()).set("use_time",null));r.setStatus("REVERSED").setReversalReason(req.reason()).setReversedByAccountId(a.getId()).setReversedTime(LocalDateTime.now());redemptionMapper.updateById(r);audit.record(a.getId(),"REDEMPTION_REVERSED","VOUCHER_REDEMPTION",id.toString(),"SUCCEEDED",req.reason());return toVO(r);}
 @Override public PageResult<VoucherRedemptionVO> list(int page,int size,boolean admin){QueryWrapper<VoucherRedemption> q=new QueryWrapper<>();if(admin)adminAuth.requirePermission(AdminPermissions.TRADE_READ);else q.eq("shop_id",operator().getShopId());Page<VoucherRedemption> p=redemptionMapper.selectPage(new Page<>(page,size),q.orderByDesc("redeemed_time","id"));return new PageResult<>(p.getRecords().stream().map(this::toVO).toList(),page,size,p.getTotal());}
 @Override public VoucherRedemptionVO get(Long id,boolean admin){VoucherRedemption r=redemptionMapper.selectById(id);if(admin)adminAuth.requirePermission(AdminPermissions.TRADE_READ);else if(r==null||!operator().getShopId().equals(r.getShopId()))throw BusinessException.notFound("REDEMPTION_NOT_FOUND","核销记录不存在");if(r==null)throw BusinessException.notFound("REDEMPTION_NOT_FOUND","核销记录不存在");return toVO(r);}
 private void validateVoucher(MerchantAccount a,UserVoucher v){if(v==null||!a.getShopId().equals(v.getShopId()))throw BusinessException.notFound("VOUCHER_NOT_FOUND","券不存在或不属于当前门店");if(!UserVoucherStatus.UNUSED.name().equals(v.getStatus())&&!UserVoucherStatus.PARTIALLY_USED.name().equals(v.getStatus()))throw BusinessException.conflict("VOUCHER_NOT_REDEEMABLE","券当前不可核销");LocalDateTime now=LocalDateTime.now();if(v.getValidBeginTime()!=null&&v.getValidBeginTime().isAfter(now)||v.getExpireTime()!=null&&!v.getExpireTime().isAfter(now))throw BusinessException.conflict("VOUCHER_NOT_IN_VALIDITY","券不在有效期");}
 private int remaining(UserVoucher v){return v.getRemainingUseCount()==null?1:v.getRemainingUseCount();}
 private long calculateDiscount(VoucherProduct p,long consumption){if(p==null)return 0;if("CASH".equals(p.getProductType()))return Math.min(consumption,p.getFaceValueAmount()==null?0:p.getFaceValueAmount());if("DISCOUNT".equals(p.getProductType())){long saved=consumption-(consumption*(p.getDiscountRateBps()==null?10000:p.getDiscountRateBps())/10000);return p.getMaximumDiscountAmount()==null?saved:Math.min(saved,p.getMaximumDiscountAmount());}return p.getPriceAmount()==null?0:p.getPriceAmount();}
 private VoucherRedemptionVO toVO(VoucherRedemption r){UserVoucher v=voucherMapper.selectById(r.getVoucherId());return new VoucherRedemptionVO(IdUtils.format(r.getId()),IdUtils.format(r.getVoucherId()),IdUtils.format(r.getShopId()),IdUtils.format(r.getMerchantAccountId()),r.getStatus(),r.getUseCount(),v==null?null:remaining(v),r.getConsumptionAmount(),r.getDiscountAmount(),r.getRedeemedTime(),r.getReversedTime(),r.getReversalReason());}
}
