spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:always}
      schema-locations: classpath:schema-init.sql
      data-locations: classpath:seed-dev.sql
logging:
  level:
    com.ray: DEBUG

ray:
  auth:
    sms:
      mode: MOCK
      mock-code: ${SMS_MOCK_CODE:123456}
