spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.ray: INFO

knife4j:
  enable: false

springdoc:
  api-docs:
    enabled: false

ray:
  merchant-invitation:
    hmac-secret: ${RAY_MERCHANT_INVITATION_HMAC_SECRET}
  qr:
    hmac-secret: ${RAY_QR_HMAC_SECRET}
  payment:
    mode: ${RAY_PAYMENT_MODE:DISABLED}
  auth:
    sms:
      mode: DISABLED
  storage:
    mode: S3
    s3:
      endpoint: ${S3_ENDPOINT}
      region: ${S3_REGION}
      bucket: ${S3_BUCKET}
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
  swagger-ui:
    enabled: false
