spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.ray: INFO

knife4j:
  enable: false

springdoc:
  api-docs:
    enabled: false

ray:
  auth:
    sms:
      mode: DISABLED
  swagger-ui:
    enabled: false
