package com.ray.controller;
import com.ray.dto.*;import com.ray.result.*;import com.ray.service.VoucherRedemptionService;import com.ray.utils.converter.IdUtils;import com.ray.vo.*;import io.swagger.v3.oas.annotations.Operation;import io.swagger.v3.oas.annotations.security.SecurityRequirement;import io.swagger.v3.oas.annotations.tags.Tag;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/v1/merchant/redemptions") @SecurityRequirement(name="BearerAuth") @Tag(name="商户核销")
public class MerchantRedemptionController {private final VoucherRedemptionService service;public MerchantRedemptionController(VoucherRedemptionService service){this.service=service;}
 @PostMapping("/previews/by-code") @Operation(summary="券码核销预览",operationId="previewMerchantRedemptionByCode") public Result<VoucherRedemptionPreviewVO> preview(@Valid @RequestBody VoucherRedemptionPreviewRequest r){return Result.ok(service.preview(r));}
 @PostMapping("/previews/by-qr-token") @Operation(summary="动态二维码核销预览",operationId="previewMerchantRedemptionByQrToken") public Result<VoucherRedemptionPreviewVO> previewQr(@RequestBody java.util.Map<String,String> body){return Result.ok(service.previewByQrToken(body.get("token")));}
 @PostMapping @Operation(summary="确认核销",operationId="confirmMerchantRedemption") public Result<VoucherRedemptionVO> confirm(@Valid @RequestBody VoucherRedemptionConfirmRequest r,@RequestHeader("Idempotency-Key") @Pattern(regexp="[A-Za-z0-9._:-]{8,128}") String key){return Result.ok(service.confirm(r,key));}
 @PostMapping("/{id}/reversal") @Operation(summary="撤销核销",operationId="reverseMerchantRedemption") public Result<VoucherRedemptionVO> reverse(@PathVariable String id,@Valid @RequestBody VoucherRedemptionReversalRequest r,@RequestHeader("Idempotency-Key") @Pattern(regexp="[A-Za-z0-9._:-]{8,128}") String key){return Result.ok(service.reverse(IdUtils.parse(id,"redemptionId"),r,key));}
 @GetMapping @Operation(summary="查询门店核销",operationId="listMerchantRedemptions") public Result<PageResult<VoucherRedemptionVO>> list(@RequestParam(defaultValue="1") @Min(1)int page,@RequestParam(defaultValue="20") @Min(1) @Max(100)int size){return Result.ok(service.list(page,size,false));}
}
